# Generated by Django 5.1.1 on 2024-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Not Available', 'Not Available')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
