# Generated by Django 5.1.1 on 2024-10-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crop_availability_status_crop_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='app.district'),
            preserve_default=False,
        ),
    ]
