# Generated by Django 5.1.1 on 2024-10-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_crop_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='district',
        ),
    ]
