# Generated by Django 5.1.1 on 2024-10-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_crop_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Not Available', 'Not Available')], max_length=50)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crop')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.district')),
            ],
            options={
                'unique_together': {('crop', 'district')},
            },
        ),
    ]
