# Generated by Django 5.1.1 on 2024-10-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cropprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(default=1, help_text='Description of the crop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='duration',
            field=models.CharField(default=1, help_text='Duration of the crop in days', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest_time',
            field=models.CharField(default=1, help_text='Time of year when the crop is ready to harvest', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='pest_issues',
            field=models.CharField(default=1, help_text='Pests that commonly affect the crop', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='weather',
            field=models.CharField(default=1, help_text='Weather conditions required for the crop', max_length=100),
            preserve_default=False,
        ),
    ]
